Repository SovereignCloudStack/rookify, pull requests merged in 2024-06, with the labels that each got.

#43 Add create configmap module
  src/rookify/modules/create_configmap/__init__.py
  src/rookify/modules/create_configmap/main.py
  src/rookify/modules/k8s_prerequisites_check/__init__.py
  src/rookify/modules/k8s_prerequisites_check/main.py
Labels: enhancement, module

#32 Prs/add create cluster module
  setup.cfg
  src/rookify/modules/create_cluster/__init__.py
  src/rookify/modules/create_cluster/main.py
  src/rookify/modules/create_cluster/templates/cluster.yaml.j2
Labels: enhancement, module

#50 Externalize `ModuleHandler` subclasses
  src/rookify/modules/ceph.py
  src/rookify/modules/cephx_auth_config/main.py
  src/rookify/modules/create_cluster/main.py
  src/rookify/modules/create_configmap/main.py
  src/rookify/modules/example/main.py
  src/rookify/modules/exception.py
  src/rookify/modules/k8s.py
  src/rookify/modules/k8s_prerequisites_check/main.py
  src/rookify/modules/module.py
  src/rookify/modules/ssh.py
  src/rookify/modules/template.py
  tests/mock_ceph.py
  tests/modules/test_example.py
Labels: enhancement, framework

#51 Feat/adding dev tools
  .gitignore
  Dockerfile
  Makefile
  config.example.yaml
  docker-compose.yml
  setup.py
Labels: work in progress

#61 Extend `load_modules()` to handle invalid modules
  src/rookify/modules/__init__.py
Labels: bug, framework
